### ISSUE TITLE
Parascorer toolkit errors

### ISSUE THREAD

**Issue by pl464** [shadowkiller33/ParaScore#1]
When I try to import the parascore package (downloaded via `pip install parascore`), I get an import error. Looking at the code, it's also not clear how to use the ParaScorer class (e.g. to run the tutorial shown in this repository's home page).

**Comment by shadowkiller33** [comment]
Thanks for pointing out this, and I'm sorry for the error. After fixing some errors and the tutorial, you may use it now. Please feel free to contact me if there's any question.
